name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Cake Action
      uses: cake-build/cake-action@v1.3.0
      with:
        script-path: build.cake
        target: publish
        
    - name: App Version
      run: |
        chmod +x ./output/self-contained/linux-x64/FilmEditor
        ./output/self-contained/linux-x64/FilmEditor --version > ./version.txt
        echo "version=$(cat ./version.txt)" >> $GITHUB_ENV
    
    - uses: papeloto/action-zip@v1
      name: win-x64 self-contained zip
      with:
        files: ./output/self-contained/win-x64/*
        dest: ./output/self-contained/FilmEditor_win-x64-self-contained.zip
    - uses: papeloto/action-zip@v1
      name: win-x86 self-contained zip
      with:
        files: ./output/self-contained/win-x86/*
        dest: ./output/self-contained/FilmEditor_win-x86-self-contained.zip
    - uses: papeloto/action-zip@v1
      name: win-arm64 self-contained zip
      with:
        files: ./output/self-contained/win-arm64/*
        dest: ./output/self-contained/FilmEditor_win-arm64-self-contained.zip
    - uses: papeloto/action-zip@v1
      name: osx-x64 self-contained zip
      with:
        files: ./output/self-contained/osx-x64/*
        dest: ./output/self-contained/FilmEditor_osx-x64-self-contained.zip
    - uses: papeloto/action-zip@v1
      name: linux-x64 self-contained zip
      with:
        files: ./output/self-contained/linux-x64/*
        dest: ./output/self-contained/FilmEditor_linux-x64-self-contained.zip
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.version }}
        release_name: Release ${{ env.version }}
        draft: false
        prerelease: false
    - name: Upload Release Asset
      id: upload-release-asset-winx64-self
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./output/self-contained/win-x64/FilmEditor_win-x64-self-contained.zip
        asset_name: FilmEditor_win-x64-self-contained.zip
        asset_content_type: application/zip
    - name: Upload Release Asset
      id: upload-release-asset-winx64-dep
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./output/framework-dependent/win-x64/FilmEditor.exe
        asset_name: FilmEditor_win-x64-dependent.exe
        asset_content_type: application/exe
    - name: Upload Release Asset
      id: upload-release-asset-winx86-self 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./output/self-contained/win-x86/FilmEditor_win-x86-self-contained.zip
        asset_name: FilmEditor_win-x86-self-contained.zip
        asset_content_type: application/zip
    - name: Upload Release Asset
      id: upload-release-asset-winx86-dep
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./output/framework-dependent/win-x86/FilmEditor.exe
        asset_name: FilmEditor_win-x86-dependent.exe
        asset_content_type: application/exe
    - name: Upload Release Asset
      id: upload-release-asset-winarm64-self
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./output/self-contained/win-arm64/FilmEditor_win-arm64-self-contained.zip
        asset_name: FilmEditor_win-arm64-self-contained.zip
        asset_content_type: application/zip
    - name: Upload Release Asset
      id: upload-release-asset-winarm64-dep
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./output/framework-dependent/win-arm64/FilmEditor.exe
        asset_name: FilmEditor_win-arm64-dependent.exe
        asset_content_type: application/exe
    - name: Upload Release Asset
      id: upload-release-asset-osxx64-self
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./output/self-contained/osx-x64/FilmEditor_osx-x64-self-contained.zip
        asset_name: FilmEditor_osx-x64-self-contained.zip
        asset_content_type: application/zip
    - name: Upload Release Asset
      id: upload-release-asset-osxx64-dep
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./output/framework-dependent/osx-x64/FilmEditor
        asset_name: FilmEditor_osx-x64-dependent
        asset_content_type: application/exe
    - name: Upload Release Asset
      id: upload-release-asset-linuxx64-self
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./output/self-contained/linux-x64/FilmEditor_linux-x64-self-contained.zip
        asset_name: FilmEditor_linux-x64-self-contained.zip
        asset_content_type: application/zip
    - name: Upload Release Asset
      id: upload-release-asset-linuxx64-dep
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./output/framework-dependent/win-x64/FilmEditor
        asset_name: FilmEditor_win-x64-dependent
        asset_content_type: application/exe
